version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: cluevia-db
    restart: always
    environment:
      POSTGRES_USER: cluevia_user
      POSTGRES_PASSWORD: xPv4Uvxu1Lnxz6fz
      POSTGRES_DB: cluevia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cluevia-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: cluevia-frontend
    restart: always
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
